- name: prepare platform for working with daily_stud_db mysqldump app (version for OpenSuse 15 and podman) 
  hosts: vm-podman-test
  become: true
  

  vars:

    - locales_default_LANG: en_US.UTF-8
    - locales_default_LC_TIME: en_GB.UTF-8
    - time_zone: ''


  tasks:

        
    - name: Get mysql-agent timer status
      ansible.builtin.systemd:
        name: 'mysql-agent.timer'
      register: mysql_agent_timer


    - name: Get mysql-agent container status
      podman_container_info:
        name: mysql-agent
      register: mysql_agent_stat  

    - debug:
        msg: "{{ mysql_agent_stat.containers }}"


    #check system on previous deployment
    - block:
      - debug:
          msg: "mysql-agent has deployed before"
      - meta: end_play
        when: "'mysql-agent' in mysql_agent_stat.containers or mysql_agent_timer.status.LoadState == 'loaded'"




    #create users
    - include_tasks: ./db_tasks/create_users.yml

    #set timezone
    - include_tasks: ./db_tasks/set_locale.yml

    #install app
    - include_tasks: ./db_tasks/install_app.yml

    #podman install
    - include_tasks: ./db_tasks/install_podman.yml
      # name: docker setup

    #make essensial directories
    - include_tasks: ./db_tasks/make_dirs.yml

    #cp configuration files
    - include_tasks: ./db_tasks/cp_files.yml

    #create secrets
    - include_tasks: ./db_tasks/create_secrets.yml

    #pull base image for build custom mysql-client
    - name: pull mysql image for build
      containers.podman.podman_image:
        name: imega/mysql-client:10.6.4

    #build custom image
    - name: Build custom image
      containers.podman.podman_image:
        name: mysql-client:10.6.4ma
        path: /opt/podman/mysql_agent/BUILD
        build:
          format: docker
  
        
    #set and configure db_timers
    - include_tasks: ./db_tasks/db_timers.yml


