- name: prepare platform for working with daily_stud_db (version for OpenSuse 15 and podman) 
  hosts: vm-podman-test
  become: true

  vars:
    - db_host: 'localhost'
    - mysql_port: '3336'  
    - tmp_pass: "mySQLPassWord"
    - mount_point: "/mnt/1c_univer"
    - moodle: "/home/moodle"
    - csv_list: ['zachetki.csv', 'level.csv', 'distsipliny_UchPlana.csv', 'spetsialnosti.csv', 'profili.csv', 'sotrudniki.csv', 'nagruzka.csv', 'studenty.csv', 'uch_plan.csv', 'facultity.csv', 'cafedry.csv', 'distsipliny.csv', 'edudom_users.csv']
    - locales_default_LANG: en_US.UTF-8
    - locales_default_LC_TIME: en_GB.UTF-8
    - time_zone: ''


  tasks:



    - name: Create container that uses the secret
      containers.podman.podman_container:
        name: showmysecret
        image: docker.io/alpine:3.14
        secrets:
          - mps02
        detach: false
        command: cat /run/secrets/mps02
      register: container

    - name: Output secret data
      debug:
        msg: '{{ container.stdout }}'




